#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 19 17:30:15 2023

@author: amberjones
"""

import matplotlib.pylab as plt
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore", message="divide by zero encountered in double_scalars")
warnings.filterwarnings("ignore", message="invalid value encountered in arcsin")

df=pd.read_parquet(r'/Users/amberjones/Documents/IRdata/dataprocessed10000')
print(df.iloc[1])
posa = df.iloc[:, 1]
poss = df.iloc[:, 3]

XA = []
YA = []
ZA = []

XS = []
YS = []
ZS = []


for n in posa:
    XA.append(n[0])
    YA.append(n[1])
    ZA.append(n[2])

for n in poss:
    XS.append(n[0])
    YS.append(n[1])
    ZS.append(n[2])

def pointDensity(X, Y, Z, detector_pos, detector_size, voxel_length):

    vol_max = np.array(detector_pos) + np.array(detector_size)
    vol_min = np.array(detector_pos) - np.array(detector_size)

    Xd = []
    Yd = []
    Zd = []

    for i, x in enumerate(X):
        #NEED TO KEEP EVENTS PAIRED SOMEHOW LINK TO OTHER DETECTORS
        if vol_min[0] < x < vol_max[0] and vol_min[1] < Y[i] < vol_max[1] and vol_min[2] < Z[i] < vol_max[2]:
            Xd.append(x)
            Yd.append(Y[i])
            Zd.append(Z[i])

    #initialise voxels
    #define number of voxels in each direction
    n_vox = int(abs(vol_min[0] - vol_max[0])/voxel_length)
    arr = np.append(np.zeros(n_vox), np.linspace(vol_min[1], vol_max[1], n_vox))

    #define voxel coordinates
    X_vox = np.append(np.linspace(vol_min[0], vol_max[0], n_vox), np.zeros(n_vox*2))
    Y_vox = np.append(arr, np.zeros(n_vox))
    Z_vox = np.append(np.zeros(n_vox*2), np.linspace(vol_min[2], vol_max[2], n_vox))
    fig = plt.figure()
    ax = fig.add_subplot(projection='3d')


    ax.scatter(X_vox, Y_vox, Z_vox, c=Z_vox, cmap=plt.cm.plasma)
    plt.show()
    V = []
    in_voxel = 0
    for i in range(len(X_vox) - 1):
        for i, x in enumerate(Xd):
            if X_vox[i] < x < X_vox[i + 1] and Y_vox[i] < Yd[i] < Y_vox[i + 1] and Z_vox[i] < Zd[i] < Z_vox[i + 1]:
                in_voxel +=1
        V.append(in_voxel)

    return V

pointDensity(XS, YS, ZS, [0, 0, 0], [30, 30, 30], 1)

'''fig = plt.figure()
ax = fig.add_subplot(projection='3d')


ax.scatter(XA, YA, ZA, c=ZA, cmap=plt.cm.plasma)
ax.scatter(XS, YS, ZS, c=ZS, cmap=plt.cm.cividis)
plt.show()'''
